### ISSUE TITLE
iOS  api  has Positioners like android?

### ISSUE THREAD

**Issue by leftsider123** [wrld3d/ios-api#22] opened 2017-10-26 09:24 UTC
iOS  api  has Positioners class like android?

**Comment by leftsider123** [comment] 2017-10-26 09:27
If I want to add a view above marker, iOS currently have any plan can be implemented?

**Comment by tompaynter03** [comment] 2017-10-26 10:08
We are currently working on a Positioners API for iOS. This API will provide the same features that are currently available in our Android API.

I will update you as the API and examples become available.

**Comment by leftsider123** [comment] 2017-10-26 10:14
thank you very much!
Every time back into the app, map data to reload, need to have a long time, is there a cache to the local API？

**Comment by tompaynter03** [comment] 2017-10-26 10:55
https://github.com/wrld3d/ios-api/issues/21#issuecomment-339628572

**Comment by tim-jenks** [comment] 2017-10-27 08:21
See issue #20 - this will add Positioners to iOS. This is in progress, and I expect it will be available in the next week or two. Closing as this is effective a duplicate of #20

**Closed as completed by tim-jenks** 2017-10-27 08:21 UTC
Labels: duplicate

**Comment by tompaynter03** [comment] 2017-11-08 13:38
A positioners API has now been added to iOS to match the Android API.
Examples can be found here:
https://wrld3d.com/ios/latest/docs/examples/position-a-view-on-the-map/
https://wrld3d.com/ios/latest/docs/examples/position-a-code-created-view-on-the-map/

Class documentation can be found here:
https://wrld3d.com/ios/latest/docs/api/Classes/WRLDPositioner.html
https://wrld3d.com/ios/latest/docs/api/Protocols/WRLDMapViewDelegate.html
