### ISSUE TITLE
Issue in eeGeo map api integration

### ISSUE THREAD

**Issue by Parveentyagi** [wrld3d/ios-api#8] opened 2017-03-30 10:23 UTC
Hi Team,

I have faced the below mentioned issues with integration in existing ios app.

Undefined symbols for architecture arm64:
  "AppRunner::TryBindDisplay(GLKView&, id<UIGestureRecognizerDelegate>&)", referenced from:
      -[EGMapView initView:] in EGMapView.o
ld: symbol(s) not found for architecture arm64

Please suggest the way to resolve that issue asap.

Thanks

**Comment by tim-jenks** [comment] 2017-03-30 10:43
Hi @Parveentyagi - could you please confirm that you have managed to build & run https://github.com/eegeo/ios-api-example ?

**Comment by Parveentyagi** [comment] 2017-03-30 11:18
Hi Tim

i have try to integrate the ios -api in my existing app according to steps mentioned on git. But face that issue AppRunner::TryBindDisplay(GLKView&, id&)", referenced from:
-[EGMapView initView:] in EGMapView.o

Please help me.
I want to done it asap, so i make a call to but paid version of sdk.

Thanks

**Comment by Parveentyagi** [comment] 2017-03-30 11:46
Hi

Please help to resolve that issue.

Thanks

**Comment by tim-jenks** [comment] 2017-03-30 13:11
Investigating and will get back to you as soon as we can.

**Comment by tim-jenks** [comment] 2017-03-30 13:15
See comments on #9 for future improvement to the iOS API to make this clearer. We will assist in the mean time.

**Comment by tim-jenks** [comment] 2017-04-05 08:03
@Parveentyagi:- We have investigated and confirmed that our ios api is functioning as expected.. Could you please confirm that you are able to build and run https://github.com/eegeo/ios-api-example 

This is important as it will confirm whether or not there is a wider issue with your development environment & our ios api. Please confirm that you are able to follow the instructions in https://github.com/eegeo/ios-api-example/blob/master/README.md and that you can compile and run on a device.

**Comment by Parveentyagi** [comment] 2017-04-05 10:55
Hi Tim,

Thanks for the update.
I am able to run the example after downloading it and folloow the steps to install the pod files.

Example app show the map for Downtown.

I am follow that link ( https://github.com/eegeo/ios-api) to integarte the eegeo iOS api in my existing app.

**Comment by tim-jenks** [comment] 2017-04-05 11:33
@Parveentyagi:- Glad to hear you can run the ios-api-example.

The error you are seeing is a linker error, it is because your project is not linking our static library. the ios-api-example project shows you how to configure your xcode project to correctly link + reference our header libraries.

Could you please try to look at the settings in the ios-api-example project and apply them to your xcode project, specifically around linking native libraries?

**Comment by Parveentyagi** [comment] 2017-04-05 11:39
Hi Tim,

Thanks for the update.

I have tried multiple time to integrate the eegeo sdk and api in my existing app. I have followed the step same as mentioned in the below mentioned url.
https://github.com/eegeo/ios-api

Could you please provide me the link to download or clone form git the latest iOS Apis and sdk.

Regards,

**Comment by tim-jenks** [comment] 2017-04-05 13:15
@Parveentyagi:- the instructions at https://github.com/eegeo/ios-api are how to build the ios-api from source, if you wished to contribute to our ios-api.  It doesn't sound like you want to do this.

You need to be following the guidance set out in ios-api-example - which is how to consume the ios-api, i.e. with a Podspec + project settings as per https://github.com/eegeo/ios-api-example

Given that you can build & run ios-api-example, you should be able to follow the steps to re-create ios-api-example until we action issue #9 which will make this clearer for people in your situation.

**Comment by Parveentyagi** [comment] 2017-04-05 13:43
Hi Tim,

Thanks for the quick response.

Now, I have follow the steps one by one mentioned on that link (https://github.com/eegeo/ios-api) as mentioned below:
1. First , I have update my pod file of the project and run pod install command.
   pod 'SMCalloutView', '~> 2.1'
    pod 'GoogleMaps', '1.10.1'
    pod 'FPPopover', '1.4.1'
After successfully, download the dependency in the project, i have run the project and it work.
2. After that, i have clone the eegeo-ios-api using that url (https://github.com/eegeo/ios-api.git) and download the sdk.
3. Now, i have drag and drop the ios-api and sdk into the project. And now i try to run the project .
4. I have get that below mentioned issues right now.
ld: library not found for -leegeo-api-host

Please suggest the next step to resolve that issue.

**Comment by Parveentyagi** [comment] 2017-04-05 14:25
Hi Tim, 

I have also tried the same steps as mentioned on that link (https://github.com/eegeo/ios-api) for example app. Drag and drop ios api and sdk in to the project and run the app. 

Then i have got that error.
ld: library not found for -leegeo-api

**Comment by tim-jenks** [comment] 2017-04-05 14:54
@Parveentyagi:- not sure if I can be much clearer - please stop following the instructions at https://github.com/eegeo/ios-api - the instructions there are if you want to build the ios-api from _source_ which you don't.

Please follow instructions at https://github.com/eegeo/ios-api-example - these instructions set you up against the binary of the ios-api from cocoapods. The Xcode + podspec in ios-api-example shows you how to setup your own project from scratch.

**Comment by Parveentyagi** [comment] 2017-04-06 08:00
HI Tim,

Thanks for the feedback.

I will try again.

**Comment by tim-jenks** [comment] 2017-04-06 08:05
Thanks @Parveentyagi:- we are also trying to reproduce the issue you are seeing - if we start from ios-api-example we are unable to reproduce. If we start from a completely blank project we can reproduce. I will send around additional information later.

Additionally, when we resolve issue #9 in the coming weeks, this will be much more straight forward.

Strongly recommend starting from ios-api-example in the mean time

**Comment by Parveentyagi** [comment] 2017-04-11 12:15
Hi Tim,

I hope you are doing well.

Please let me know any update on the issue mentioned above related to eegeo ios api integration in a existing/new project.

Thanks

**Comment by Parveentyagi** [comment] 2017-04-18 08:34
Hi Tim,

I hope you are doing well.

Please let me know any update on the issue mentioned above related to eegeo ios api integration.

Thanks

**Comment by tim-jenks** [comment] 2017-04-18 09:02
Hi @Parveentyagi issue #9 is underway and is due in the 1.1 milestone

**Comment by tim-jenks** [comment] 2017-09-13 08:58
Closing as #9 is complete

**Closed as completed by tim-jenks** 2017-09-13 08:58 UTC
Labels: question
