### ISSUE TITLE
- (void)mapView:(WRLDMapView *)mapView didTapMarker:(WRLDMarker *)marker

### ISSUE THREAD

**Issue by leftsider123** [wrld3d/ios-api#15] opened 2017-06-29 03:13 UTC
hello,team!
- (void) mapView mapView: (WRLDMapView *) didTapMarker (WRLDMarker *) marker
This method for processing, will delay two seconds, is this why?

**Comment by jonty-dawson** [comment] 2017-06-29 08:26
Hi - I've tried to reproduce this in our examples app, using the "Select a marker" example:
https://github.com/wrld3d/ios-api-example/blob/master/ApiSamples/Samples/MarkerTappedNotification.m
See also:
https://wrld3d.com/ios/latest/docs/examples/interact-with-markers/

This didn't exhibit any significant delay, when running on an iPhone 5s, iOS 9.2.1.
A very small delay is expected, as we wait to ensure that the user gesture is not a double-tap before dispatching the single-tap gesture.

If you are still experiencing this issue, could you provide some more information about your test conditions please?

**Comment by leftsider123** [comment] 2017-06-30 03:21
Hi!
A bit of a slight delay。
You can  look at the effect of GIF figure, click after little time delay, the console will print data。
![tap](https://user-images.githubusercontent.com/9531871/27719598-2d3b1e98-5d86-11e7-9f89-4447e1ea3ce8.gif)

**Comment by tim-jenks** [comment] 2017-06-30 08:14
Could you try to reproduce on a real device? The simulator is notoriously poor performance with respect to 3D graphics, and may be contributing to frame delays due to this.

**Comment by jonty-dawson** [comment] 2017-06-30 08:15
Hi - thanks for the additional information.
It looks like you are running the app on a Simulator device. It think it is likely that the delay you are seeing is due to this. I've just tried running on a simulated iPhone 6 like your gif, and see a similar delay.
Please note that performance when running on Simulator is not representative of the performance on an actual iOS device.
Have you tried running on a physical iOS device to see if the issue still occurs?

**Comment by leftsider123** [comment] 2017-06-30 08:18
Hi!
 same when run on a real device. because I look console change.
The simulator will affect the console print?

**Comment by jonty-dawson** [comment] 2017-06-30 08:25
Could you let us know the device model and iOS version that you are testing on please? It might let us reproduce the issue here.

**Comment by leftsider123** [comment] 2017-06-30 08:36
iPhone 6s Plus version 10.3.2

**Comment by jonty-dawson** [comment] 2017-06-30 08:55
Thanks, we'll investigate further

**Comment by jonty-dawson** [comment] 2017-07-04 10:08
An update on this - we haven't been able to test on the exact device and iOS version that you are using, but have tested on:
iPhone 6, iOS 8.3
iPhone 7 Plus, iOS 10.2.1

We haven't been able to reproduce the problem that you are reporting. We see a delay of approximately 300ms, which is expected due to waiting for double-tap gesture to be detected.

**Comment by tim-jenks** [comment] 2017-09-13 08:52
Closing issue as this is cannot reproduce and no update for a quarter

**Closed as completed by tim-jenks** 2017-09-13 08:52 UTC
Labels: cannot reproduce
